version: "3"

services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./:/workspace
