@baseUrl = {{$processEnv GATSBY_API_SECURITY}}/api/jwt

// @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###

@refreshId = {{login.response.body.$.data.refreshId}}

// @name refresh
POST {{baseUrl}}/refresh
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "id": "{{refreshId}}"
}
